# Generated by Django 3.2.3 on 2023-03-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Restaurant_Suggestion',
        ),
        migrations.DeleteModel(
            name='TopCustomers',
        ),
    ]
